export const rolePermissionMap: Record<string, string[]> = {
  platform_admin: [
    'auth.manage_sessions',
    'iam.manage_roles',
    'users.read',
    'tenant.read',
    'counterparties.read',
    'directions.read',
    'courses.read',
    'courses.publish',
    'courses.archive',
    'groups.read',
    'enrollments.read',
    'assessment.tests.read',
    'assessment.question_banks.read',
    'assessment.question_banks.write',
    'assessment.questions.read',
    'assessment.questions.write',
    'assessment.tests.read',
    'assessment.tests.write',
    'assessment.tests.publish',
    'assessment.attempts.read',
    'assessment.attempts.take',
    'assessment.results.read',
    'assessment.assignments.read',
    'assessment.assignments.write',
    'assessment.submissions.submit',
    'assessment.reviews.review',
    'assessment.read.cross_learner',
    'learners.act_as'
  ],
  tenant_admin: [
    'auth.manage_sessions',
    'iam.manage_roles',
    'users.read',
    'tenant.read',
    'counterparties.read',
    'directions.read',
    'courses.read',
    'groups.read',
    'enrollments.read',
    'assessment.tests.read',
    'assessment.results.read',
    'assessment.assignments.read',
    'assessment.read.cross_learner',
    'learners.act_as'
  ],
  manager: [
    'users.read',
    'tenant.read',
    'counterparties.read',
    'directions.read',
    'courses.read',
    'groups.read',
    'enrollments.read',
    'assessment.tests.read',
    'assessment.results.read',
    'assessment.assignments.read',
    'assessment.reviews.review',
    'assessment.read.cross_learner',
    'learners.act_as'
  ],
  methodist: [
    'users.read',
    'tenant.read',
    'directions.read',
    'courses.read',
    'groups.read',
    'assessment.question_banks.read',
    'assessment.question_banks.write',
    'assessment.questions.read',
    'assessment.questions.write',
    'assessment.tests.read',
    'assessment.tests.write',
    'assessment.tests.publish',
    'assessment.assignments.read',
    'assessment.assignments.write',
    'assessment.read.cross_learner',
    'learners.act_as'
  ],
  learner: [
    'enrollments.read',
    'assessment.tests.read',
    'assessment.attempts.read',
    'assessment.attempts.take',
    'assessment.submissions.submit',
    'assessment.results.read',
    'assessment.assignments.read'
  ]
};

export const resolveRolePermissions = (roleCodes: string[]): string[] => [
  ...new Set(roleCodes.flatMap((roleCode) => rolePermissionMap[roleCode] ?? []))
];
