/** Keys match InMemoryMvpState property names (JSON store collections). */
export const MVP_COLLECTIONS = [
  'counterparties',
  'learners',
  'directions',
  'courses',
  'courseVersions',
  'modules',
  'materials',
  'groups',
  'groupCourses',
  'enrollments',
  'enrollmentStatusHistory',
  'materialProgress',
  'moduleProgress',
  'courseProgress',
  'questionBanks',
  'questions',
  'answerOptions',
  'tests',
  'testQuestions',
  'attempts',
  'attemptAnswers',
  'examResults',
  'assignments',
  'assignmentSubmissions',
  'assignmentReviews',
  'bulkEnrollmentIdempotency',
  'bulkImportIdempotency',
  'commissions',
  'commissionMembers',
  'courseDocumentSets'
] as const;

export type MvpCollection = (typeof MVP_COLLECTIONS)[number];
